import sqlite3
from datetime import datetime
import random


def init_db():
    conn = sqlite3.connect("results/radiologist_reports.db")
    cursor = conn.cursor()
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS radiologist_reports (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            feedback_id TEXT UNIQUE,
            datetime TEXT,
            radiologist_name TEXT,
            phone TEXT,
            email TEXT,
            comment TEXT,
            mri_tumor_class TEXT,
            ct_tumor_result TEXT
        )
    """)
    conn.commit()
    conn.close()


def generate_feedback_id():
    date_part = datetime.now().strftime("%Y%m%d")
    random_part = random.randint(100000, 999999)
    return f"FB-{date_part}-{random_part}"


def save_radiologist_data(feedback_id, name, phone, email, comment, mri_tumor_class, ct_tumor_result):
    conn = sqlite3.connect("results/radiologist_reports.db")
    cursor = conn.cursor()
    cursor.execute("""
        INSERT INTO radiologist_reports
        (feedback_id, datetime, radiologist_name, phone, email, comment, mri_tumor_class, ct_tumor_result)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?)
    """, (
        feedback_id,
        datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        name, phone, email, comment, mri_tumor_class, ct_tumor_result
    ))
    conn.commit()
    conn.close()


def save_text_report(feedback_id, ct_tumor_result, mri_tumor_class, rad_name, rad_phone, rad_email, rad_comment):
    return f"""
        MRI AND CT TUMOR DETECTION REPORT
        ----------------------------------

        Feedback ID : {feedback_id}
        Date        : {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

        CT Status   : {ct_tumor_result}
        MRI Status  : {mri_tumor_class}

        Radiologist Details
        -------------------
        Name    : {rad_name}
        Phone   : {rad_phone}
        Email   : {rad_email}

        Comments:
        {rad_comment}

        This report was generated by an AI-assisted system.
        Consult a medical professional for final diagnosis.
    """


# Initialize DB automatically when module is imported
init_db()
